### ISSUE TITLE
prerequisites: Microsoft Visual C++ 2008 Redistributable

### ISSUE THREAD

**Issue by micsutka** [maaaaz/thc-hydra-windows#1]
Dear maaaaz,

Thank you for your effort for making hydra for windows.
I've downloaded the latest version, extracted the zip, then run the hydra.exe.
I'm using Windows XP SP3 32 bit.
It can not start but gives an error message:
"The application failed to initialize properly (0xc0150002)"
I've found this error message in event viewer:
"Dependent Assembly Microsoft.VC90.CRT could not be found and Last Error was The referenced assembly is not installed on your system"

The solution:
I had to install Microsoft Visual C++ Redistributable Package (x86).
At first, I tried the 2005 version from this link:
https://www.microsoft.com/en-us/download/details.aspx?id=3387
This did not solve the problem, so I tried to install the 2008 version from this link:
https://www.microsoft.com/en-us/download/details.aspx?id=29
After this I can run hydra.exe without any error messages.

Please, consider to mention this prerequisite of thc-hydra-windows.

Thanks,
Robert

**Comment by maaaaz** [comment]
Hi Robert,

Thank you for reporting that prerequisites.
I have updated the README with the MS package link.

Cheers.
