### ISSUE TITLE
thc hydra v8.5 when is killed or crashed does not save any "hydra.restore" file behind 

### ISSUE THREAD

**Issue by dumbo0** [maaaaz/thc-hydra-windows#10]
thc hydra v8.5 for windows when process is killed or crashed does not save any "hydra.restore" file behind only  Control-C can do that
I download yesterday hydra from: https://github.com/maaaaz/thc-hydra-windows/releases/tag/v8.5
Here a small youtube video(2,5 mb) where I'm doing a test and demonstrating that hydra can not save hydra.restore when process is killed or pc restarted: https://youtu.be/r_kmHhGuUGQ
How can i solve this?becouse this is a big disadvantage.
thank you

**Comment by maaaaz** [comment]
Do you have the same issue with :
* The Linux version (on a kali for example) ?
* [Older Windows hydra](https://github.com/maaaaz/thc-hydra-windows/releases) versions ?

If the answers are "yes" then please it report it on hydra's github,

**Comment by dumbo0** [comment]
I never use Linux i love Windows and yes i know that Linux is better but i prefer Windows
I tried all Windows versions: 6.1 , 8.0 ,8.1 ,v8.5 all have same problem

**Comment by maaaaz** [comment]
So I guess it comes from hydra, not from the windows compilation.
Please report your issue on hydra's github.

Cheers.

**Comment by dumbo0** [comment]
ok i will psot there this issue,you think this can be fixed?

**Comment by maaaaz** [comment]
No the official THC-hydra github is : https://github.com/vanhauser-thc/thc-hydra
I'm not the maintainer of hydra.

**Comment by dumbo0** [comment]
12 horus ago i psot the issue there and someone deleted it ! :P haha what to do? post again ?

**Comment by dumbo0** [comment]
i post there again and i was deleted,what to do ?
