### ISSUE TITLE
I always receive this type of issue when i run -m servers.txt

### ISSUE THREAD

**Issue by dumbo0** [maaaaz/thc-hydra-windows#13]
I always receive this type of issue when i run  -m servers.txt
here the entire syntax: `hydra -V -l admin -p 123456 -t 4 -w 10 -f -M ips.txt rdp`

and this is the error,why?how can i solve this?hydra is not able to run more then 100 servers or what?:
```
*** stack smashing detected ***:  terminated
       0 [main] hydra 17964 cygwin_exception::open_stackdumpfile: Dumping stack trace to hydra.exe.stackdump
```

**Comment by maaaaz** [comment]
Hello,
I don't know, please attach the stacktrace dump.

Cheers.

**Comment by dumbo0** [comment]
ips.txt ( contains 120 ips) here the stacktrace dump: https://hostr.co/iDshJhxmOmGd

**Comment by dumbo0** [comment]
Another short question i know default parallels are: 16 and waiting time 30 right?by defalut,my question is can i set more parallels?how do i know what is the maximum?
thank yuo!

**Comment by maaaaz** [comment]
Try with the latest release.
