### ISSUE TITLE
Could you please share your build steps/scripts/configure flags?

### ISSUE THREAD

**Issue by sgeto** [maaaaz/thc-hydra-windows#17]
Thanks in advance.

**Comment by maaaaz** [comment]
Please try to compile yourself with the following directions and post here your difficulties, I will happily help:
* https://www.quora.com/How-can-I-install-THC-Hydra-with-Cygwin
* http://kaoticcreations.blogspot.fr/2011/06/how-to-setup-working-thchydra-and.html
* http://kpoyagahack.blogspot.com/2017/09/crack-with-thc-hydra-linux-terminal-on.html


Cheers

**Comment by maaaaz** [comment]
Adding this for reference: https://github.com/maaaaz/thc-hydra-windows/wiki
