### ISSUE TITLE
ERROR: Incorrect login. Please try again

### ISSUE THREAD

**Issue by chernyy-korol** [maaaaz/thc-hydra-windows#18]
ERROR: Incorrect login. Please try again this is the error message that i got on thc-hydra but not always some times my command line dosent work ...!! 
![thc-hydra](https://user-images.githubusercontent.com/36448618/36156656-94a88692-108c-11e8-8b1b-cbeefd914f26.PNG)
i try to change the patch & stuff & it's not working

**Comment by Reelix** [comment]
The ":" in the "ERROR:" is causing it to look for a new parameter - Try just do "Incorrect login"

**Comment by chernyy-korol** [comment]
i already try this ...!!! 
![capture](https://user-images.githubusercontent.com/36448618/36163380-17c4d06a-109e-11e8-9b6e-441491b7a968.PNG)

**Comment by chernyy-korol** [comment]
its a bug in i well fix by my self on source code , its not done when u
clode the ticket xD

2018-06-06 14:44 GMT-04:00 Thomas D. <notifications@github.com>:
