### ISSUE TITLE
Problem with new hydra

### ISSUE THREAD

**Issue by xmtsh** [maaaaz/thc-hydra-windows#19]
In older version I had first:

[ATTEMPT] target smtp - login "XXX" - pass "XXX" - 1 of X [child 0] (0/0)

and next:

[STATUS] X tries/min, X tries in XX:XXh, XXXXXX todo in XXXXXXX:Xh, 16 active

I your new version i have only ATTEMPT but i haven't STATUS and finally "0 passwords found". What is the answer? (in older vers i had problem with cygwin.dlls)

**Comment by maaaaz** [comment]
No idea. Have you tried the Linux version to compare ?
