### ISSUE TITLE
missing services

### ISSUE THREAD

**Issue by micsutka** [maaaaz/thc-hydra-windows#2]
Hi,

I've found some services supported by the official (https://www.thc.org/thc-hydra/) thc-hydra, but unsupported by thc-hydra-windows:
- AFP
- Firebird
- NCP
- SAP/R3
- Subversion

Why are these services not supported by thc-hydra-windows?

Thanks,
Robert

**Comment by micsutka** [comment]
I think I've found the answer.
This fork of hydra has been compiled without some libraries:
[ERROR] Compiled without LIBFIREBIRD support, module not available!
[ERROR] Compiled without LIBNCP support, module not available!
[ERROR] Compiled without LIBAFP support, module not available!

**Comment by maaaaz** [comment]
Yes, I did not compile hydra with those modules: I did try once but the resulting compiled hydra.exe was not stable.
Well I'll might try again in next releases.
