### ISSUE TITLE
hydra closing INSTANTLY when I try to open

### ISSUE THREAD

**Issue by acujl** [maaaaz/thc-hydra-windows#20]
title

**Comment by eladrebrab** [comment]
On my Win 10 Pro x64, it's doing the same thing.

I get a Command prompt that opens then closes rapidly and that's all. I've tried running the Compatibility Troubleshooter but without success!

I'd love to get Hydra for Windows working.

**Comment by maaaaz** [comment]
Start a cmd.exe interpreter before and launch "hydra.exe" to see the output

**Comment by eladrebrab** [comment]
OK, tried that.
Text based Hydra started normally in the Command prompt and output the Syntax and Options...since it was started without any parameters.
No sign of any GUI.

**Comment by maaaaz** [comment]
Yes no GUI

**Comment by eladrebrab** [comment]
So maaaaz, will Hydra for Windows ever work on Win 10 Pro X64 ?

**Comment by eladrebrab** [comment]
Hey Thomas, I don't understand your reply...Yes no GUI.


Are you confirming that there is a problem ?


Or are you saying that it's normal and that we shouldn't expect a GUI for WIN 10 Pro x64 ?


Cheers...Dale

________________________________
