### ISSUE TITLE
win 10 64bit, i have VS 2015， VScode on my computer, also the .NET framework is included，but i can not run the hydra.exe

### ISSUE THREAD

**Issue by mozp1962** [maaaaz/thc-hydra-windows#25]
win 10 64bit, i have VS 2015， VScode on my computer, also the .NET framework is included，but i can not run the hydra.exe, when i double click, nothing shows up

and when i run it in the cmd, with  ./hydra.exe -I user http://<--ip address-->, it shows unknow service

**Comment by maaaaz** [comment]
Hello,

Indeed there is no `http` service, you have to use `http-get` or `http-form-post`:
```
> hydra.exe -l toto -p toto http://<website>
Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2019-05-12 11:52:31
[ERROR] There is no service "http", most likely you mean one of the many web modules, e.g. http-get or http-form-post. Read it up!
```

Cheers
