### ISSUE TITLE
New version of hydra

### ISSUE THREAD

**Issue by Ghost-Recon131** [maaaaz/thc-hydra-windows#26]
Mind if you recompile for the newest version of hydra? Or what tool did you use to compile it? Is it Visual studio community with the C++ extension? Thanks!

**Comment by maaaaz** [comment]
Hello,

I just released it.
Cheers.

**Comment by Ghost-Recon131** [comment]
Thanks! btw do you know how to compile the hydra gtk? I can only do that on linux but not windows.

**Comment by maaaaz** [comment]
I have never tried on Windows so I don't know.

**Comment by Ghost-Recon131** [comment]
ok thanks anyway
