### ISSUE TITLE
RDP module not working

### ISSUE THREAD

**Issue by CG-root** [maaaaz/thc-hydra-windows#27]
```
C:\Users\bob\Desktop\>hydra.exe -l test -p test rdp://123.123.123.123
Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-06-24 15:31:03
[ERROR] Compiled without FREERDP2 support, module not available!
```

**Comment by Robin6464** [comment]
In cygwin you can compile thc-hydra with the RDP2 module enabled.

**Comment by maaaaz** [comment]
Thanks for the insights @Robin6464 !

**Comment by Robin6464** [comment]
In the previous post maybe I said vaguely. So the hydra 8.5 version has the rpd module enabled and the rdp password cracking running on windows NT/XP... (hydra 8.7_dev does not work correctly with rdp). For RDP breaking running on windows 7/8/10 you need the RDP2 module (libfreerdp2)

**Comment by maaaaz** [comment]
It should be fixed as the latest release comes with `libfreerdp2`.

Cheers.
