### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by thelonleyone** [maaaaz/thc-hydra-windows#29]
Can you make it to scan with GPU if it;s possible.
Thank you

**Comment by maaaaz** [comment]
@thelonleyone, you mean "make `hydra` use the GPU instead of CPU" ?
If it is what you mean, hydra is not a password cracker like `hashcat`, it's a credentials bruteforcer. So it has nothing to do with a need of computation power.

**Comment by thelonleyone** [comment]
Aha ok but its so slow scaning i use and other crackers like rdp that scans fast, anyway thank you

**Comment by maaaaz** [comment]
Don't hesitate to report on the original `hydra` repository: https://github.com/vanhauser-thc/thc-hydra
