### ISSUE TITLE
fork for children isnt working

### ISSUE THREAD

**Issue by fredpmontenegro** [maaaaz/thc-hydra-windows#30]
How do I fix this?

**Comment by djerrystyle** [comment]
some questions:
15011642 [main] hydra 1428 dofork: child -1 - forked process 31668 died unexpectedly, retry 0, exit code 0xC0000142, errno 11

**Comment by maaaaz** [comment]
Hello,
Try the [new release](https://github.com/maaaaz/thc-hydra-windows/releases/latest), compiled for x64, it might help preventing these crashes.

Cheers
