### ISSUE TITLE
Hydra closing instantly

### ISSUE THREAD

**Issue by cookiep1ayz** [maaaaz/thc-hydra-windows#31]
I have been trying to open hydra for a while and gone through all the different compatibility versions, i also tried to open it with cmd but when opening with cmd i get this error 2 [main] hydra 1210 cygwin_exception::open_stackdumpfile: Dumping stack trace to hydra.exe.stackdump when i try to run the code on cmd after the application opens and instantly closes again please help

**Comment by EgiAprilianto** [comment]
same

**Comment by cookiep1ayz** [comment]
Kinda getting annoying at this point

**Comment by JoatmonX** [comment]
Same experience.  When run from a command line, looks and acts like command line version.

**Comment by JoatmonX** [comment]
Ah.  It IS a command line tool, meant to be run from CLI.  I followed a link here that showed a Windows GUI.

**Comment by maaaaz** [comment]
@cookiep1ayz, @EgiAprilianto : what precise command did you type that led to hydra crashing ?

**Comment by EgiAprilianto** [comment]
![image](https://user-images.githubusercontent.com/52872948/84940231-bbb14380-b109-11ea-8e86-183e3a4a7480.png)

I just type 'hydra'

**Comment by maaaaz** [comment]
can you try `hydra.exe -h`

**Comment by cookiep1ayz** [comment]
Try what?

**Comment by zimmer84** [comment]
> can you try `hydra.exe -h`

![photo_2020-06-18_14-50-46](https://user-images.githubusercontent.com/61014027/84999592-319dc500-b173-11ea-881a-c7e40ff1e1fa.jpg)

**Comment by zimmer84** [comment]
![photo_2020-06-18_14-50-46](https://user-images.githubusercontent.com/61014027/85001284-4713ee80-b175-11ea-8079-4e10b75046ad.jpg)

**Comment by maaaaz** [comment]
Weird, I can't explain.
So use the version 9.0 if it works, the current 9.1 version is still in development.

**Comment by maaaaz** [comment]
Hello,
Try the [new release](https://github.com/maaaaz/thc-hydra-windows/releases/latest), compiled for x64, it might help preventing these crashes.

Cheers
