### ISSUE TITLE
Would you mind to provide source code?

### ISSUE THREAD

**Issue by slayerlab** [maaaaz/thc-hydra-windows#32]
Hi Thomaz,

I came across this repository a week ago, but I didn't use it because of the source code missing. So, I am trying to migrate the THC-Hydra to Windows with my adjustments. I do not want to use all resources that it provides.
In light of that, knowing the Hydra is an open-source, would you mind helping the community providing your source code?

 
Thanks in advance. 👍

**Comment by maaaaz** [comment]
Hello @slayerlab,
I don't have a specific source code, I just [compiled](https://github.com/maaaaz/thc-hydra-windows/issues/17) the original version.

Cheers.
