### ISSUE TITLE
THC Hydra does not work ...

### ISSUE THREAD

**Issue by Xprogrammer777** [maaaaz/thc-hydra-windows#36]
I tried to run Hydra by a simple double click, the window opens and closes very quickly, and also try to launch it from the cmd nothing works .... Then I followed this tutorial: https://www.youtube.com/watch?v=-eY1IocjHAM
but impossible to put a list of password, Hydra indicates that it is not found, would you have a solution?

Thank you,
Xprogrammer777

**Comment by Reelix** [comment]
Hydra is a command-line based application. You need to run it from the command line (cmd or wt), or use a batch file (Not really recommended)

**Comment by Xprogrammer777** [comment]
Thank you for your reply!
I have already tried running Hydra from the cmd by doing the following:

1- I enter cd followed by path to Hydra
2-I write hydra.exe
3-The file opens but it is not possible to enter an command to Hydra
Can you explain to me how please proceed?
PS: In addition I have already tested the graphical version of Hydra for Windows, but once again impossible to execute it a message indicates that it is missing a DLL package

Thanks again,
Xprogrammer777

**Comment by maaaaz** [comment]
cf. https://github.com/maaaaz/thc-hydra-windows/issues/31, https://github.com/maaaaz/thc-hydra-windows/issues/24, https://github.com/maaaaz/thc-hydra-windows/issues/20,
