### ISSUE TITLE
Hydra does not (always) open ....

### ISSUE THREAD

**Issue by Xprogrammer777** [maaaaz/thc-hydra-windows#37]
Hello,

I tried before opening Hydra to launch cmd.exe
nothing works the hydra window opens and closes suddenly I also try to run it from the cmd by typing "cd" followed by Hydra path then by typing hydra.exe , Hydra opens but cannot enter a command
(the cmd remit "C: \ WINDOWS \ system32>").
Can you explain the process to open Hydra please?

Thanks again,
Xprogrammer777

**Comment by CharonXXI** [comment]
Same Issue!!

**Comment by Xprogrammer777** [comment]
Hi CharonXXI, 


I found how to run THC Hydra under Windows 10, here is how I proceeded:

-I extract Hydra in a folder on the desktop
-I copy the path to the folder where Hydra is located
-I open the cmd I write cd then I do ctrl + v
-I write Hydra -h
-hydra opens, to enter an order you must start with Hydra.

**Comment by CharonXXI** [comment]
> Hi CharonXXI,
> 
> I found how to run THC Hydra under Windows 10, here is how I proceeded:
> 
> -I extract Hydra in a folder on the desktop
> -I copy the path to the folder where Hydra is located
> -I open the cmd I write cd then I do ctrl + v
> -I write hydra -h
> -Hydra opens, to enter an order you must start with Hydra.

I got it :) thank you
