### ISSUE TITLE
bump to 8.3 ?

### ISSUE THREAD

**Issue by FrancYescO** [maaaaz/thc-hydra-windows#4]

**Comment by maaaaz** [comment]
I'll try to see whether I manage to compile it.

**Comment by FrancYescO** [comment]
Thanks :)

If you also put few howto steps can be a good thing

**Comment by lightpencil** [comment]
YES it would be great if you could put few howto steps

**Comment by euphrat1ca** [comment]
yes, i used the Cygwin . it still have some error like this : terminals database is inaccessible

**Comment by maaaaz** [comment]
v8.5 is out
