### ISSUE TITLE
Publish the build scripts

### ISSUE THREAD

**Issue by JJK96** [maaaaz/thc-hydra-windows#42]
Hi,

Could you publish the scripts you used to build this repository. This has multiple advantages:

1. People can build it themselves, so they don't have to trust your build
2. If you show your build pipeline, this shows that the binaries relate directly to the thc-hydra source and can therefore be trusted.
3. Others can maintain this repository easily if you decide not to maintain it anymore

**Comment by maaaaz** [comment]
https://github.com/maaaaz/thc-hydra-windows/wiki

https://github.com/maaaaz/thc-hydra-windows/issues/39
