### ISSUE TITLE
DYLIB error after fresh install

### ISSUE THREAD

**Issue by tschijvenaars** [maaaaz/thc-hydra-windows#45]
Getting the following after a fresh install:
`dyld[52886]: Library not loaded: /usr/lib/libpcre2-8.0.dylib`

and the following:

`Referenced from: <BD0536E4-645A-3038-92FB-C77AFDBB0C63> /opt/homebrew/Cellar/hydra/9.5_1/bin/hydra
  Reason: tried: '/usr/lib/libpcre2-8.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libpcre2-8.0.dylib' (no such file), '/usr/lib/libpcre2-8.0.dylib' (no such file, not in dyld cache), '/usr/local/lib/libpcre2-8.0.dylib' (no such file)
zsh: abort `

No idea why it happens, got this after running one command run succesfully (so it worked, then I aborted, next time i ran an hydra command it stopped working)

Running version 9.5_1

**Comment by maaaaz** [comment]
Please report this bug here: https://github.com/vanhauser-thc/thc-hydra
