### ISSUE TITLE
trojan/rat

### ISSUE THREAD

**Issue by ashjk6** [maaaaz/thc-hydra-windows#49]
all antiviruses i checked, virus total also, they said trojan/rat

**Comment by maaaaz** [comment]
Well, it is not.

https://github.com/maaaaz/thc-hydra-windows?tab=readme-ov-file#disclaimer--licence

**Comment by Andrew-A10** [comment]
cyber, i took the risk and downloaded it and it is not malware. but if you are still skeptical i get it lol 😭
