### ISSUE TITLE
[VERBOSE] Could not create an SSL session

### ISSUE THREAD

**Issue by icytwat** [maaaaz/thc-hydra-windows#6]
I have been getting this error after doing everything right, someone help me with this please

[VERBOSE] Could not create an SSL session: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by maaaaz** [comment]
Hello,

There are multiple possible troubles:
* Your target needs TLS client authentication: afaik hydra does not support client cert. If such please: 
  * Open an issue on [thc-hydra github](https://github.com/vanhauser-thc/thc-hydra)
  * Try to use [socat as a a TLS proxy] as socat supports client cert authentication  (https://www.owasp.org/index.php/Testing_for_Weak_SSL/TLS_Ciphers,_Insufficient_Transport_Layer_Protection_(OTG-CRYPST-001)#Example_8._Testing_via_HTTP_proxy)
* Your target does not support SSLv2/SSLv3 and the cygssl lib has a bug with recent protocols and ciphers. You can try to:
  * Turn on the debug mode to hydra with the `-d` option
  * Specify to use SSL to hydra with the `-S` option
  * Specify to use old protocols to hydra with the `  -O        use old SSL v2 and v3` option

Cheers.
