### ISSUE TITLE
about hydra v8.5 - 06/05/2017 resume problem!

### ISSUE THREAD

**Issue by dumbo0** [maaaaz/thc-hydra-windows#9]
e.g.: if i run hidra mmm hydra.resume appears after 2500 lines,how can i change that to 1000? becouse if someone restarts my VPS after 2 min.then hydra.restore file don't appear yet,i would like to know more about resume,when it appears?

**Comment by maaaaz** [comment]
I'm not sure to understand fully the problem but I don't think I can make something.
Post your issue on the [hydra github](https://github.com/vanhauser-thc/thc-hydra).

**Comment by dumbo0** [comment]
well i wanna say that hydra.restore file not updates if pc is restarted or process is killed and that is not a good thing,how can i fix that?theni will delete my comments and writte there
p.s.
hydra.restore updates from time to time or when u stop it pressing CTRL+C ,can u make it updates hydra.restore even when process is killed or pc restarted?
i use hydra last version for windows
thank you
